@startuml SoliQueue_Sprint2
left to right direction
skinparam actorStyle awesome

skinparam package {
    BackgroundColor White
    BorderColor #2C3E50
}

skinparam usecase {
    BackgroundColor #E8F6F3
    BorderColor #117864
    ArrowColor #117864
}

actor "Candidat" as C
actor "Administrateur" as Admin

package "Sprint 2 – Fonctionnalités Avancées (SoliQueue)" {

    ' ========================
    ' Améliorations Candidat
    ' ========================
    usecase "Recevoir notifications visuelles prioritaires" as UC1
    
    C -- UC1

    ' ========================
    ' Améliorations Administrateur
    ' ========================
    usecase "Importer/Exporter les candidats" as UC5
    usecase "Exporter les sessions" as UC6

    Admin -- UC5
    Admin -- UC6

    usecase "S'authentifier via cin" as Auth1
    usecase "S'authentifier " as Auth2

    UC1 ..> Auth1 : <<include>>
    UC5 ..> Auth2 : <<include>>
    UC6 ..> Auth2 : <<include>>
}

@enduml
