@startuml QueueManagement_Sprint2
skinparam actorStyle awesome
left to right direction

skinparam package {
    BackgroundColor White
    BorderColor #2C3E50
}

skinparam usecase {
    BackgroundColor #E8F6F3
    BorderColor #117864
    ArrowColor #117864
}

actor "Candidat" as C
actor "Formateur" as F
actor "Administrateur" as Admin

package "Sprint 2 – Fonctionnalités Avancées" {

    usecase "Notification quelques minutes avant son tour" as UC1
    usecase "Notification lors de son tour" as UC2
    usecase "Voir si le ticket a été annulé ou reporté" as UC3

    C -- UC1
    C -- UC2
    C -- UC3

   
    usecase "Authentification Formateur" as UC4
    usecase "Envoyer automatiquement notifications pour reports ou annulations" as UC6
    usecase "Voir les statistiques des sessions" as UC7

    
    F -- UC6
    F -- UC7
 
    UC6 ..> UC4 : <<include>>
    UC7 ..> UC4 : <<include>>


    ' ========================
    ' Espace Administrateur
    ' ========================
    usecase "Authentification Admin" as UC8
    usecase "Recevoir alertes sur absences ou problèmes" as UC9
    usecase "Consulter les statistiques globales" as UC10
    usecase "Réorganisation/priorisation automatique" as UC11

    Admin -- UC9
    Admin -- UC10
    Admin -- UC11
    UC9 ..> UC8 : <<include>>
    UC10 ..> UC8 : <<include>>
    UC11 ..> UC8 : <<include>>
}

@enduml