@startuml
left to right direction

title Cas d utilisation global - Gestion des files d attente

' Acteurs alignés verticalement
actor Candidat
actor "formateur" as Formateur
actor Administrateur as Admin

rectangle "Systeme de gestion des files d attente" {

  ' --- Cas Candidat ---
  usecase "Prendre un ticket" as UC1
  usecase "Consulter sa position" as UC2
  usecase "Recevoir notifications avant son tour" as UC3
  usecase "Annuler / Reporter ticket" as UC4
  usecase "Historique et suivi des tickets" as UC16

  ' --- Cas Equipe ---
  usecase "Authentification formateur " as UC17
  usecase "Reorganiser file" as UC6
  usecase "Mettre a jour statut tickets" as UC7
  usecase "Notifications pour candidats" as UC8
  usecase "Statistiques des sessions" as UC9

  ' --- Cas Admin ---
  usecase "Authentification admin " as UC10
  usecase "Création et gestion des sessions" as UC11
  usecase "Suivi de la file d’attente globale" as UC12
  usecase "Consulter statistiques" as UC13
  usecase "Notifications administratives" as UC14
  usecase "Réorganisation/priorisation automatique" as UC15
}

' Relations Candidat
Candidat -- UC1
Candidat -- UC2
Candidat -- UC3
Candidat -- UC4
Candidat -- UC16

' Relations Formateur

Formateur -- UC6
Formateur -- UC7
Formateur -- UC8
Formateur -- UC9

UC6 ..> UC17 : <<include>>
UC7 ..> UC17 : <<include>>
UC8 ..> UC17 : <<include>>
UC9 ..> UC17 : <<include>>

' Relations Admin
Admin -- UC11
Admin -- UC12
Admin -- UC13
Admin -- UC14
Admin -- UC15

UC11 ..> UC10 : <<include>>
UC12 ..> UC10 : <<include>>
UC13 ..> UC10 : <<include>>
UC14 ..> UC10 : <<include>>
UC15 ..> UC10 : <<include>>

@enduml