@startuml SoliQueue_UseCase_Admin
left to right direction
skinparam actorStyle awesome
skinparam shadowing false

skinparam usecase {
    BackgroundColor #E8F6F3
    BorderColor #117864
}

skinparam nodesep 40
skinparam ranksep 50

' Acteurs Web
actor "Administrateur" as Admin
actor "Formateur" as Formateur

' Acteur Mobile (Candidat)
actor "Mobile" as Mob

'=====================
' Admin Use Cases (Web)
'=====================
usecase "Tableau de bord global" as UC1
usecase "Gérer les entretiens" as UC2
usecase "Affecter les candidats (Drag & Drop)" as UC3
usecase "Gérer les candidats" as UC4
usecase "Gérer les formateurs" as UC5
usecase "Consulter les statistiques" as UC6
usecase "Importer/Exporter les candidats" as UC7
usecase "Exporter les sessions" as UC8



'=====================
' Formateur Use Cases (Web)
'=====================
usecase "Rejoindre un entretien" as UC9
usecase "Appeler le candidat suivant" as UC10
usecase "Mettre à jour statut (Présent/Absent/Terminé)" as UC11
usecase "Consulter la file d'attente active" as UC12
usecase "Déplacer ou prioriser certains candidats si nécessaire." as UC13

'=====================
' Mobile API (Candidat)
'=====================
usecase "Consommer API (Synchronisation File)" as API

'=====================
' Authentification
'=====================
usecase "S'authentifier" as Auth
usecase "S'authentifier" as Auth2

'=====================
' Relations Admin
'=====================
Admin -- UC1
Admin -- UC2
Admin -- UC3
Admin -- UC4
Admin -- UC5
Admin -- UC6
Admin -- UC7
Admin -- UC8

'=====================
' Relations Formateur
'=====================
Formateur -- UC9
Formateur -- UC10
Formateur -- UC11
Formateur -- UC12
Formateur -- UC13

'=====================
' Relations Mobile
'=====================
Mob -- API


'=====================
' Authentification includes
'=====================
UC1 ..> Auth : <<include>>
UC2 ..> Auth : <<include>>
UC3 ..> Auth : <<include>>
UC4 ..> Auth : <<include>>
UC5 ..> Auth : <<include>>
UC6 ..> Auth : <<include>>


UC7 ..> Auth : <<include>>
UC8 ..> Auth : <<include>>
UC9 ..> Auth2 : <<include>>
UC10 ..> Auth2 : <<include>>
UC11 ..> Auth2 : <<include>>
UC12 ..> Auth2 : <<include>>
UC13 ..> Auth2 : <<include>>

usecase "Interagir avec l'assistant IA " as UC14
Admin -- UC14
UC14 ..> Auth : <<include>>

usecase "Interagir avec l'assistant IA (Actions)" as UC15
Formateur -- UC15
UC15 ..> Auth2 : <<include>>


@enduml